export default [
  {
    key: 'wishlist',
    value: 0,
    text: 'wishlist',
    title: 'wishlist',
    icon: 'cloud',
  },
  {
    key: 'applied',
    value: 1,
    text: 'applied',
    title: 'applied',
    icon: 'send outline',
  },
  {
    key: 'phone interview',
    value: 2,
    text: 'phone interview',
    title: 'phone interview',
    icon: 'phone',
  },
  {
    key: 'pre on site',
    value: 3,
    text: 'pre on site',
    title: 'pre on site',
    icon: 'road',
  },
  {
    key: 'interview',
    value: 4,
    text: 'interview',
    title: 'interview',
    icon: 'marker',
  },
  {
    key: 'offer',
    value: 5,
    text: 'offer',
    title: 'offer',
    icon: 'dollar',
  },
  {
    key: 'accepted offer',
    value: 6,
    text: 'accepted offer',
    title: 'accepted offer',
    icon: 'checkmark',
  },
];
